name: Publish to PyPI

on:
  push:
    tags:
      - "v*"   # ejemplo: v0.1.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # requerido si usas Trusted Publishing (OIDC)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      # PUBLICACIÓN (elige uno de los 2 enfoques):

      # 1) TOKEN PyPI: crea el secreto PYPI_API_TOKEN en GitHub (Settings > Secrets > Actions)
      - name: Publish to PyPI (token)
        if: ${{ secrets.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # 2) TRUSTED PUBLISHING (OIDC): sin secretos (actívalo en PyPI: "Trusted Publishers")
      - name: Publish to PyPI (trusted publisher)
        if: ${{ secrets.PYPI_API_TOKEN == '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
